// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
)

// Injectors from wire.go:

func AppInjector(ctx context.Context) (Baz, error) {
	foo := NewFoo()
	bar := NewBar(foo)
	baz, err := NewBaz(ctx, bar)
	if err != nil {
		return Baz{}, err
	}
	return baz, nil
}

// wire.go:

var PFoo = wire.NewSet(NewFoo, NewBar, NewBaz) //将有相互依赖关系的对象组合在一起，减少Injector的生成
